### ISSUE TITLE
@0.1.4 not including typings

### ISSUE THREAD

**Issue by brauliolledo** [NicolasThierion/aspectjs#35]
First of all, this is an amazing project that has been hugely useful for one of my current projects, so thanks  @NicolasThierion !

**Describe the bug**

Version @0.1.4 onwards don't include expected typings on commons/dist folder. This impedes taking advantage of Typescript when using the latest version of the library. 

@0.1.2 does include them.

**To Reproduce**

1. Install latest version from npm
2. Import any object or function from @aspectjs
3. IDE not recognizing typings

**Expected behavior**
Being allowed to use typings

Thanks

**Comment by NicolasThierion** [comment]
Hi.

Thank you for the issue. I've not been publicly active on this project for a long time, but your message has been encouraging for me. 

Under the hood, I managed a complete rewrite of this project, that I hope will be mantainable more easily. You may try it out to see if it still fits your needs.

Tested today, the typings are working as expected.
